// This file contains exports neessary when LittleJS is used as a module

// TODO: Add setters and getters for all variables that devs will need to modify and are currently internal
const setTileSizeDefault = (v2) => tileSizeDefault = v2;
const setRandSeed = (s) => randSeed = s;
const setCameraPos = (pos) => cameraPos = pos;
const setCameraScale = (scale) => cameraScale = scale;
const setGravity = (g) => gravity = g;

const getMainContext = () => mainContext;
const getOverlayCanvas = () => overlayCanvas;
const getCameraPos = () => cameraPos;
const getCameraScale = () => cameraScale;
const getMousePos = () => mousePos;
const getMouseWheel = () => mouseWheel;
const getUsingGamepad = () => isUsingGamepad;
const getTileCollisionSize = () => tileCollisionSize;

// This is a full list of everything in engine.all except the gl_ constants
// TODO: Remove internal variables from this list
export {
	// ---------- Custom methods
	setTileSizeDefault,
	setRandSeed,
	setCameraPos,
	setCameraScale,
	setGravity,
	getMainContext,
	getOverlayCanvas,
	getCameraPos,
	getCameraScale,
	getMousePos,
	getMouseWheel,
	getUsingGamepad,
	getTileCollisionSize,
	// ---------- Engine Methods and Variables
	// Globals
	debug,
	enableAsserts,
	debugPointSize,
	showWatermark,
	godMode,
	// Debug
	debugPrimitives,
	debugOverlay,
	debugPhysics,
	debugRaycast,
	debugParticles,
	debugGamepads,
	debugMedals,
	debugTakeScreenshot,
	//downloadLink,
	//ASSERT,
	debugRect,
	debugCircle,
	debugPoint,
	debugLine,
	debugAABB,
	debugText,
	debugClear,
	debugSaveCanvas,
	debugInit,
	debugUpdate,
	debugRender,
	// Utilities
	PI,
	abs,
	min,
	max,
	sign,
	mod,
	clamp,
	percent,
	lerp,
	smoothStep,
	nearestPowerOfTwo,
	isOverlapping,
	wave,
	formatTime,
	// Random
	rand,
	randInt,
	randSign,
	randInCircle,
	randVector,
	randColor,
	randSeed, // Add get/set
	randSeeded,
	// More utilities
	vec2,
	Vector2,
	colorRGBA,
	colorHSLA,
	Color,
	Timer,
	// Settings -- Could all use get/set methods
	canvasMaxSize,
	canvasFixedSize,
	cavasPixelated,
	fontDefault,
	tileSizeDefault,
	tileFixBleedScale,
	objectDefaultSize,
	enablePhysicsSolver,
	objectDefaultMass,
	objectDefaultDamping,
	objectDefaultAngleDamping,
	objectDefaultElasticity,
	objectDefaultFriction,
	objectMaxSpeed,
	gravity,
	particleEmitRateScale,
	cameraPos,
	cameraScale,
	glEnable,
	glOverlay,
	gamepadsEnable,
	gamepadDirectionEmulateStick,
	inputWASDEmulateDirection,
	touchGamepadEnable,
	touchGamepadAnalog,
	touchGamepadSize,
	touchGamepadAlpha,
	vibrateEnable,
	soundVolume,
	soundEnable,
	soundDefaultRange,
	soundDefaultTaper,
	medalDisplayTime,
	medalDisplaySlideTime,
	medalDisplayWidth,
	medalDisplayHeight,
	medalDisplayIconSize,
	// Base
	EngineObject,
	// Draw
	tileImage,
	mainCanvas,
	mainContext,
	overlayCanvas,
	overlayContext,
	mainCanvasSize,
	screenToWorld,
	worldToScreen,
	drawTile,
	drawRect,
	drawTileScreenSpace,
	drawRectScreenSpace,
	drawLine,
	drawCanvas2D,
	setBlendMode,
	drawTextScreen,
	drawText,
	engineFontImage,
	FontImage,
	isFullscreen,
	toggleFullscreen,
	// Input
	keyIsDown,
	keyWasPressed,
	keyWasReleased,
	clearInput,
	mouseIsDown,
	mouseWasPressed,
	mouseWasReleased,
	mousePos,
	mousePosScreen,
	mouseWheel,
	isUsingGamepad,
	preventDefaultInput,
	gamepadIsDown,
	gamepadWasPressed,
	gamepadWasReleased,
	gamepadStick,
	//inputData,
	inputUpdate,
	inputUpdatePost,
	// onkeydown,
	// onkeyup,
	//remapKeyCode,
	// onmousedown,
	// onmouseup,
	// onmousemove,
	// onwheel,
	// oncontextmenu,
	mouseToScreen,
	//stickData,
	gamepadsUpdate,
	vibrate,
	vibrateStop,
	isTouchDevice,
	//touchGamepadTimer,
	touchGamepadCreate,
	touchGamepadRender,
	// sound
	Sound,
	Music,
	playAudioFile,
	speak,
	speakStop,
	getNoteFrequency,
	audioContext,
	playSamples,
	zzfx,
	//zzfxR,
	//zzfxG,
	//zzfxM,
	// tiles
	tileCollision,
	tileCollisionSize,
	initTileCollision,
	setTileCollisionData,
	getTileCollisionData,
	tileCollisionTest,
	tileCollisionRaycast,
	TileLayerData,
	TileLayer,
	// Particles
	ParticleEmitter,
	Particle,
	// Other
	medals,
	medalsPreventUnlock,
	newgrounds,
	medalsDisplayQueue,
	medalsInit,
	Medal,
	medalsRender,
	Newgrounds,
	//CryptoJS,
	// WebGL
	glCanvas,
	glContext,
	glTileTexture,
	glActiveTexture,
	glShader,
	glPositionData,
	glColorData,
	glBatchCount,
	glBatchAdditive,
	glAdditive,
	glInit,
	glSetBlendMode,
	glSetTexture,
	glCompileShader,
	glCreateProgram,
	glCreateBuffer,
	glCreateTexture,
	glPreRender,
	glFlush,
	glCopyToContext,
	glDraw,
	// Various "gl_" constants (ignored)
	// Engine
	engineName,
	engineVersion,
	frameRate,
	timeDelta,
	engineObjects,
	//engineObjectsCollide,
	frame,
	time,
	timeReal,
	paused,
	//frameTimeLastMS,
	averageFPS,
	//drawCount,
	//styleBody,
	//styleCanvas,
	engineInit,
	enginePreRender,
	engineObjectsUpdate,
	engineObjectsDestroy,
	engineObjectsCallback,
};
