/**
 * LittleJS Module Export
 */

export
{
	// Engine
	engineName,
	engineVersion,
	frameRate,
	timeDelta,
	engineObjects,
	frame,
	time,
	timeReal,
	paused,
	getPaused,
	setPaused,
	engineInit,
	engineObjectsUpdate,
	engineObjectsDestroy,
	engineObjectsCollect,
	engineObjectsCallback,
	engineObjectsRaycast,
	engineAddPlugin,

	// Globals
	debug,
	debugOverlay,
	showWatermark,

	// Debug
	ASSERT,
	debugRect,
	debugPoly,
	debugCircle,
	debugPoint,
	debugLine,
	debugOverlap,
	debugText,
	debugClear,
	debugScreenshot,
	debugSaveCanvas,
	debugSaveText,
	debugSaveDataURL,
	debugShowErrors,
	debugVideoCaptureIsActive,
	debugVideoCaptureStart,
	debugVideoCaptureStop,

	// Settings
	cameraPos,
	cameraAngle,
	cameraScale,
	canvasColorTiles,
	canvasMaxSize,
	canvasFixedSize,
	canvasPixelated,
	overlayCanvasPixelated,
	tilesPixelated,
	fontDefault,
	showSplashScreen,
	headlessMode,
	tileSizeDefault,
	tileFixBleedScale,
	enablePhysicsSolver,
	objectDefaultMass,
	objectDefaultDamping,
	objectDefaultAngleDamping,
	objectDefaultRestitution,
	objectDefaultFriction,
	objectMaxSpeed,
	gravity,
	particleEmitRateScale,
	glEnable,
	gamepadsEnable,
	gamepadDirectionEmulateStick,
	inputWASDEmulateDirection,
	touchGamepadEnable,
	touchGamepadAnalog,
	touchGamepadSize,
	touchGamepadAlpha,
	vibrateEnable,
	soundEnable,
	soundVolume,
	soundDefaultRange,
	soundDefaultTaper,
	medalDisplayTime,
	medalDisplaySlideTime,
	medalDisplaySize,

	// Setters for globals
	setCameraPos,
	setCameraAngle,
	setCameraScale,
	setCanvasColorTiles,
	setCanvasMaxSize,
	setCanvasFixedSize,
	setCanvasPixelated,
	setOverlayCanvasPixelated,
	setTilesPixelated,
	setFontDefault,
	setShowSplashScreen,
	setHeadlessMode,
	setGLEnable,
	setTileSizeDefault,
	setTileFixBleedScale,
	setEnablePhysicsSolver,
	setObjectDefaultMass,
	setObjectDefaultDamping,
	setObjectDefaultAngleDamping,
	setObjectDefaultRestitution,
	setObjectDefaultFriction,
	setObjectMaxSpeed,
	setGravity,
	setParticleEmitRateScale,
	setTouchInputEnable,
	setGamepadsEnable,
	setGamepadDirectionEmulateStick,
	setInputWASDEmulateDirection,
	setTouchGamepadEnable,
	setTouchGamepadAnalog,
	setTouchGamepadSize,
	setTouchGamepadAlpha,
	setVibrateEnable,
	setSoundEnable,
	setSoundVolume,
	setSoundDefaultRange,
	setSoundDefaultTaper,
	setMedalDisplayTime,
	setMedalDisplaySlideTime,
	setMedalDisplaySize,
	setMedalsPreventUnlock,
	setShowWatermark,
	setDebugKey,

	// Utilities
	PI,
	abs,
	min,
	max,
	sign,
	mod,
	clamp,
	percent,
	distanceWrap,
	lerpWrap,
	distanceAngle,
	lerpAngle,
	lerp,
	smoothStep,
	nearestPowerOfTwo,
	isOverlapping,
	isIntersecting,
	wave,
	formatTime,
	fetchJSON,

	// Random
	rand,
	randInt,
	randSign,
	randInCircle,
	randVec2,
	randColor,

	// Utility Classes
	RandomGenerator,
	Vector2,
	Color,
	Timer,
	vec2,
	rgb,
	hsl,
	isColor,
	isVector2,
	isNumber,

	// Default Colors
	WHITE,
	CLEAR_WHITE,
	BLACK,
	CLEAR_BLACK,
	GRAY,
	RED,
	ORANGE,
	YELLOW,
	GREEN,
	CYAN,
	BLUE,
	PURPLE,
	MAGENTA,

	// Draw
	textureInfos,
	tile,
	TileInfo,
	TextureInfo,
	mainCanvas,
	mainContext,
	overlayCanvas,
	overlayContext,
	mainCanvasSize,
	screenToWorld,
	worldToScreen,
	drawTile,
	drawRect,
	drawLine,
	drawPoly,
	drawEllipse,
	drawCircle,
	drawCanvas2D,
	drawText,
	drawTextOverlay,
	drawTextScreen,
	setBlendMode,
	combineCanvases,
	engineFontImage,
	FontImage,
	isFullscreen,
	toggleFullscreen,
	setCursor,
	getCameraSize,

	// WebGL
	glCanvas,
	glContext,
	glCompileShader,
	glCopyToContext,
	glCreateProgram,
	glCreateTexture,
	glDeleteTexture,
	glSetTextureData,
	glDraw,
	glFlush,
	glSetTexture,
	glSetAntialias,
	glClearCanvas,
	glAntialias,
	glShader, 
	glActiveTexture, 
	glArrayBuffer, 
	glGeometryBuffer, 
	glPositionData, 
	glColorData, 
	glInstanceCount, 
	glAdditive, 
	glBatchAdditive,

	// Input
	keyIsDown,
	keyWasPressed,
	keyWasReleased,
	keyDirection,
	inputClear,
	inputClearKey,
	mouseIsDown,
	mouseWasPressed,
	mouseWasReleased,
	mousePos,
	mousePosScreen,
	mouseDelta,
	mouseDeltaScreen,
	mouseWheel,
	isUsingGamepad,
	inputPreventDefault,
	setInputPreventDefault,
	gamepadIsDown,
	gamepadWasPressed,
	gamepadWasReleased,
	gamepadStick,
	gamepadsUpdate,
	vibrate,
	vibrateStop,
	isTouchDevice,
	pointerLockRequest,
	pointerLockExit,
	pointerLockIsActive,

	// Audio
	Sound,
	SoundWave,
	playAudioFile,
	speak,
	speakStop,
	getNoteFrequency,
	playSamples,
	zzfx,
	zzfxG,
	zzfxR,
	audioContext,

	// Base Object
	EngineObject,

	// Tiles
	tileCollisionLayers,
	tileCollisionGetData,
	tileCollisionTest,
	tileCollisionRaycast,
	tileCollisionLoad,
	TileLayerData,
	CanvasLayer,
	TileLayer,
	TileCollisionLayer,

	// Particles
	ParticleEmitter,
	Particle,

	// Medals
	medals,
	medalsPreventUnlock,
	medalsInit,
	Medal,
};